name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clean up repository before deploy
        run: |
          rm -rf builder.js LICENSE readme.md
          find . -type f \( -name "*.json" -o -name "*.txt" \) -delete

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Minify CSS
        run: |
          npx esbuild style.css --minify --allow-overwrite --outfile=style.css

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4